-- ----------------------------------------------------------------------
--
-- TIMEZONE TABLES
--
-- ----------------------------------------------------------------------

DROP TABLE IF EXISTS TimeZones;
CREATE TABLE IF NOT EXISTS TimeZones
(
	i_timezone	INT UNSIGNED NOT NULL,
	iso_3166_1_a2	CHAR(2) NOT NULL DEFAULT'',
	description	VARCHAR(64) NOT NULL,
	comments	VARCHAR(255) NOT NULL DEFAULT '',
	format		VARCHAR(64) NOT NULL DEFAULT '',
	PRIMARY KEY (i_timezone),
	UNIQUE KEY (description)
) TYPE=InnoDB;

INSERT INTO TimeZones VALUES
	(0, '--', 'DEFAULT', '', '%e %b %Y %T'),
	(1, 'AD', 'Europe/Andorra', '', '%e %b %Y %T'),
	(2, 'AE', 'Asia/Dubai', '', '%e %b %Y %T'),
	(3, 'AF', 'Asia/Kabul', '', '%e %b %Y %T'),
	(4, 'AG', 'America/Antigua', '', '%b %e, %Y %r'),
	(5, 'AI', 'America/Anguilla', '', '%b %e, %Y %r'),
	(6, 'AL', 'Europe/Tirane', '', '%e %b %Y %T'),
	(7, 'AM', 'Asia/Yerevan', '', '%e %b %Y %T'),
	(8, 'AN', 'America/Curacao', '', '%b %e, %Y %r'),
	(9, 'AO', 'Africa/Luanda', '', '%e %b %Y %T'),
	(10, 'AQ', 'Antarctica/McMurdo', 'McMurdo Station, Ross Island', '%e %b %Y %T'),
	(11, 'AQ', 'Antarctica/South_Pole', 'Amundsen-Scott Station, South Pole', '%e %b %Y %T'),
	(12, 'AQ', 'Antarctica/Palmer', 'Palmer Station, Anvers Island', '%e %b %Y %T'),
	(13, 'AQ', 'Antarctica/Mawson', 'Mawson Station, Holme Bay', '%e %b %Y %T'),
	(14, 'AQ', 'Antarctica/Davis', 'Davis Station, Vestfold Hills', '%e %b %Y %T'),
	(15, 'AQ', 'Antarctica/Casey', 'Casey Station, Bailey Peninsula', '%e %b %Y %T'),
	(16, 'AQ', 'Antarctica/Vostok', 'Vostok Station, S Magnetic Pole', '%e %b %Y %T'),
	(17, 'AQ', 'Antarctica/DumontDUrville', 'Dumont-d\'Urville Base, Terre Adelie', '%e %b %Y %T'),
	(18, 'AQ', 'Antarctica/Syowa', 'Syowa Station, E Ongul I', '%e %b %Y %T'),
	(19, 'AR', 'America/Buenos_Aires', 'E Argentina (BA, DF, SC, TF)', '%b %e, %Y %r'),
	(20, 'AR', 'America/Rosario', 'NE Argentina (SF, ER, CN, MN, CC, FM, LP, CH)', '%b %e, %Y %r'),
	(21, 'AR', 'America/Cordoba', 'W Argentina (CB, SA, TM, LR, SJ, SL, NQ, RN)', '%b %e, %Y %r'),
	(22, 'AR', 'America/Jujuy', 'Jujuy (JY)', '%b %e, %Y %r'),
	(23, 'AR', 'America/Catamarca', 'Catamarca (CT)', '%b %e, %Y %r'),
	(24, 'AR', 'America/Mendoza', 'Mendoza (MZ)', '%b %e, %Y %r'),
	(25, 'AS', 'Pacific/Pago_Pago', '', '%e %b %Y %T'),
	(26, 'AT', 'Europe/Vienna', '', '%e %b %Y %T'),
	(27, 'AU', 'Australia/Lord_Howe', 'Lord Howe Island', '%e %b %Y %T'),
	(28, 'AU', 'Australia/Hobart', 'Tasmania', '%e %b %Y %T'),
	(29, 'AU', 'Australia/Melbourne', 'Victoria', '%e %b %Y %T'),
	(30, 'AU', 'Australia/Sydney', 'New South Wales - most locations', '%e %b %Y %T'),
	(31, 'AU', 'Australia/Broken_Hill', 'New South Wales - Yancowinna', '%e %b %Y %T'),
	(32, 'AU', 'Australia/Brisbane', 'Queensland - most locations', '%e %b %Y %T'),
	(33, 'AU', 'Australia/Lindeman', 'Queensland - Holiday Islands', '%e %b %Y %T'),
	(34, 'AU', 'Australia/Adelaide', 'South Australia', '%e %b %Y %T'),
	(35, 'AU', 'Australia/Darwin', 'Northern Territory', '%e %b %Y %T'),
	(36, 'AU', 'Australia/Perth', 'Western Australia', '%e %b %Y %T'),
	(37, 'AW', 'America/Aruba', '', '%b %e, %Y %r'),
	(38, 'AZ', 'Asia/Baku', '', '%e %b %Y %T'),
	(39, 'BA', 'Europe/Sarajevo', '', '%e %b %Y %T'),
	(40, 'BB', 'America/Barbados', '', '%b %e, %Y %r'),
	(41, 'BD', 'Asia/Dhaka', '', '%e %b %Y %T'),
	(42, 'BE', 'Europe/Brussels', '', '%e %b %Y %T'),
	(43, 'BF', 'Africa/Ouagadougou', '', '%e %b %Y %T'),
	(44, 'BG', 'Europe/Sofia', '', '%e %b %Y %T'),
	(45, 'BH', 'Asia/Bahrain', '', '%e %b %Y %T'),
	(46, 'BI', 'Africa/Bujumbura', '', '%e %b %Y %T'),
	(47, 'BJ', 'Africa/Porto-Novo', '', '%e %b %Y %T'),
	(48, 'BM', 'Atlantic/Bermuda', '', '%e %b %Y %T'),
	(49, 'BN', 'Asia/Brunei', '', '%e %b %Y %T'),
	(50, 'BO', 'America/La_Paz', '', '%b %e, %Y %r'),
	(51, 'BR', 'America/Noronha', 'Atlantic islands', '%b %e, %Y %r'),
	(52, 'BR', 'America/Belem', 'Amapa, E Para', '%b %e, %Y %r'),
	(53, 'BR', 'America/Fortaleza', 'NE Brazil (MA, PI, CE, RN, PR)', '%b %e, %Y %r'),
	(54, 'BR', 'America/Recife', 'Pernambuco', '%b %e, %Y %r'),
	(55, 'BR', 'America/Araguaina', 'Tocantins', '%b %e, %Y %r'),
	(56, 'BR', 'America/Maceio', 'Alagoas, Sergipe', '%b %e, %Y %r'),
	(57, 'BR', 'America/Sao_Paulo', 'S & SE Brazil (BA, GO, DF, MG, ES, RJ, SP, PR, SC, RS)', '%b %e, %Y %r'),
	(58, 'BR', 'America/Cuiaba', 'Mato Grosso, Mato Grosso do Sul', '%b %e, %Y %r'),
	(59, 'BR', 'America/Porto_Velho', 'W Para, Rondonia', '%b %e, %Y %r'),
	(60, 'BR', 'America/Boa_Vista', 'Roraima', '%b %e, %Y %r'),
	(61, 'BR', 'America/Manaus', 'E Amazonas', '%b %e, %Y %r'),
	(62, 'BR', 'America/Eirunepe', 'W Amazonas', '%b %e, %Y %r'),
	(63, 'BR', 'America/Rio_Branco', 'Acre', '%b %e, %Y %r'),
	(64, 'BS', 'America/Nassau', '', '%b %e, %Y %r'),
	(65, 'BT', 'Asia/Thimphu', '', '%e %b %Y %T'),
	(66, 'BW', 'Africa/Gaborone', '', '%e %b %Y %T'),
	(67, 'BY', 'Europe/Minsk', '', '%e %b %Y %T'),
	(68, 'BZ', 'America/Belize', '', '%b %e, %Y %r'),
	(69, 'CA', 'America/St_Johns', 'Newfoundland Island', '%b %e, %Y %r'),
	(70, 'CA', 'America/Halifax', 'Atlantic Time - Nova Scotia (most places), NB, W Labrador, E Quebec & PEI', '%b %e, %Y %r'),
	(71, 'CA', 'America/Glace_Bay', 'Atlantic Time - Nova Scotia - places that did not observe DST 1966-1971', '%b %e, %Y %r'),
	(72, 'CA', 'America/Goose_Bay', 'Atlantic Time - E Labrador', '%b %e, %Y %r'),
	(73, 'CA', 'America/Montreal', 'Eastern Time - Ontario & Quebec - most locations', '%b %e, %Y %r'),
	(74, 'CA', 'America/Nipigon', 'Eastern Time - Ontario & Quebec - places that did not observe DST 1967-1973', '%b %e, %Y %r'),
	(75, 'CA', 'America/Thunder_Bay', 'Eastern Time - Thunder Bay, Ontario', '%b %e, %Y %r'),
	(76, 'CA', 'America/Pangnirtung', 'Eastern Standard Time - Pangnirtung, Nunavut', '%b %e, %Y %r'),
	(77, 'CA', 'America/Iqaluit', 'Eastern Standard Time - east Nunavut', '%b %e, %Y %r'),
	(78, 'CA', 'America/Rankin_Inlet', 'Eastern Standard Time - central Nunavut', '%b %e, %Y %r'),
	(79, 'CA', 'America/Winnipeg', 'Central Time - Manitoba & west Ontario', '%b %e, %Y %r'),
	(80, 'CA', 'America/Rainy_River', 'Central Time - Rainy River & Fort Frances, Ontario', '%b %e, %Y %r'),
	(81, 'CA', 'America/Cambridge_Bay', 'Central Time - west Nunavut', '%b %e, %Y %r'),
	(82, 'CA', 'America/Regina', 'Central Standard Time - Saskatchewan - most locations', '%b %e, %Y %r'),
	(83, 'CA', 'America/Swift_Current', 'Central Standard Time - Saskatchewan - midwest', '%b %e, %Y %r'),
	(84, 'CA', 'America/Edmonton', 'Mountain Time - Alberta, east British Columbia & west Saskatchewan', '%b %e, %Y %r'),
	(85, 'CA', 'America/Yellowknife', 'Mountain Time - central Northwest Territories', '%b %e, %Y %r'),
	(86, 'CA', 'America/Inuvik', 'Mountain Time - west Northwest Territories', '%b %e, %Y %r'),
	(87, 'CA', 'America/Dawson_Creek', 'Mountain Standard Time - Dawson Creek & Fort Saint John, British Columbia', '%b %e, %Y %r'),
	(88, 'CA', 'America/Vancouver', 'Pacific Time - west British Columbia', '%b %e, %Y %r'),
	(89, 'CA', 'America/Whitehorse', 'Pacific Time - south Yukon', '%b %e, %Y %r'),
	(90, 'CA', 'America/Dawson', 'Pacific Time - north Yukon', '%b %e, %Y %r'),
	(91, 'CC', 'Indian/Cocos', '', '%e %b %Y %T'),
	(92, 'CD', 'Africa/Kinshasa', 'west Dem. Rep. of Congo', '%e %b %Y %T'),
	(93, 'CD', 'Africa/Lubumbashi', 'east Dem. Rep. of Congo', '%e %b %Y %T'),
	(94, 'CF', 'Africa/Bangui', '', '%e %b %Y %T'),
	(95, 'CG', 'Africa/Brazzaville', '', '%e %b %Y %T'),
	(96, 'CH', 'Europe/Zurich', '', '%e %b %Y %T'),
	(97, 'CI', 'Africa/Abidjan', '', '%e %b %Y %T'),
	(98, 'CK', 'Pacific/Rarotonga', '', '%e %b %Y %T'),
	(99, 'CL', 'America/Santiago', 'most locations', '%b %e, %Y %r'),
	(100, 'CL', 'Pacific/Easter', 'Easter Island & Sala y Gomez', '%e %b %Y %T'),
	(101, 'CM', 'Africa/Douala', '', '%e %b %Y %T'),
	(102, 'CN', 'Asia/Harbin', 'north Manchuria', '%e %b %Y %T'),
	(103, 'CN', 'Asia/Shanghai', 'China coast', '%e %b %Y %T'),
	(104, 'CN', 'Asia/Chungking', 'China mountains', '%e %b %Y %T'),
	(105, 'CN', 'Asia/Urumqi', 'Tibet & Xinjiang', '%e %b %Y %T'),
	(106, 'CN', 'Asia/Kashgar', 'Eastern Turkestan', '%e %b %Y %T'),
	(107, 'CO', 'America/Bogota', '', '%b %e, %Y %r'),
	(108, 'CR', 'America/Costa_Rica', '', '%b %e, %Y %r'),
	(109, 'CU', 'America/Havana', '', '%b %e, %Y %r'),
	(110, 'CV', 'Atlantic/Cape_Verde', '', '%e %b %Y %T'),
	(111, 'CX', 'Indian/Christmas', '', '%e %b %Y %T'),
	(112, 'CY', 'Asia/Nicosia', '', '%e %b %Y %T'),
	(113, 'CZ', 'Europe/Prague', '', '%e %b %Y %T'),
	(114, 'DE', 'Europe/Berlin', '', '%e %b %Y %T'),
	(115, 'DJ', 'Africa/Djibouti', '', '%e %b %Y %T'),
	(116, 'DK', 'Europe/Copenhagen', '', '%e %b %Y %T'),
	(117, 'DM', 'America/Dominica', '', '%b %e, %Y %r'),
	(118, 'DO', 'America/Santo_Domingo', '', '%b %e, %Y %r'),
	(119, 'DZ', 'Africa/Algiers', '', '%e %b %Y %T'),
	(120, 'EC', 'America/Guayaquil', 'mainland', '%b %e, %Y %r'),
	(121, 'EC', 'Pacific/Galapagos', 'Galapagos Islands', '%e %b %Y %T'),
	(122, 'EE', 'Europe/Tallinn', '', '%e %b %Y %T'),
	(123, 'EG', 'Africa/Cairo', '', '%e %b %Y %T'),
	(124, 'EH', 'Africa/El_Aaiun', '', '%e %b %Y %T'),
	(125, 'ER', 'Africa/Asmera', '', '%e %b %Y %T'),
	(126, 'ES', 'Europe/Madrid', 'mainland', '%e %b %Y %T'),
	(127, 'ES', 'Africa/Ceuta', 'Ceuta & Melilla', '%e %b %Y %T'),
	(128, 'ES', 'Atlantic/Canary', 'Canary Islands', '%e %b %Y %T'),
	(129, 'ET', 'Africa/Addis_Ababa', '', '%e %b %Y %T'),
	(130, 'FI', 'Europe/Helsinki', '', '%e %b %Y %T'),
	(131, 'FJ', 'Pacific/Fiji', '', '%e %b %Y %T'),
	(132, 'FK', 'Atlantic/Stanley', '', '%e %b %Y %T'),
	(133, 'FM', 'Pacific/Yap', 'Yap', '%e %b %Y %T'),
	(134, 'FM', 'Pacific/Truk', 'Truk (Chuuk)', '%e %b %Y %T'),
	(135, 'FM', 'Pacific/Ponape', 'Ponape (Pohnpei)', '%e %b %Y %T'),
	(136, 'FM', 'Pacific/Kosrae', 'Kosrae', '%e %b %Y %T'),
	(137, 'FO', 'Atlantic/Faeroe', '', '%e %b %Y %T'),
	(138, 'FR', 'Europe/Paris', '', '%e %b %Y %T'),
	(139, 'GA', 'Africa/Libreville', '', '%e %b %Y %T'),
	(140, 'GB', 'Europe/London', 'Great Britain', '%e %b %Y %T'),
	(141, 'GB', 'Europe/Belfast', 'Northern Ireland', '%e %b %Y %T'),
	(142, 'GD', 'America/Grenada', '', '%b %e, %Y %r'),
	(143, 'GE', 'Asia/Tbilisi', '', '%e %b %Y %T'),
	(144, 'GF', 'America/Cayenne', '', '%b %e, %Y %r'),
	(145, 'GH', 'Africa/Accra', '', '%e %b %Y %T'),
	(146, 'GI', 'Europe/Gibraltar', '', '%e %b %Y %T'),
	(147, 'GL', 'America/Scoresbysund', 'east Greenland', '%b %e, %Y %r'),
	(148, 'GL', 'America/Godthab', 'southwest Greenland', '%b %e, %Y %r'),
	(149, 'GL', 'America/Thule', 'northwest Greenland', '%b %e, %Y %r'),
	(150, 'GM', 'Africa/Banjul', '', '%e %b %Y %T'),
	(151, 'GN', 'Africa/Conakry', '', '%e %b %Y %T'),
	(152, 'GP', 'America/Guadeloupe', '', '%b %e, %Y %r'),
	(153, 'GQ', 'Africa/Malabo', '', '%e %b %Y %T'),
	(154, 'GR', 'Europe/Athens', '', '%e %b %Y %T'),
	(155, 'GS', 'Atlantic/South_Georgia', '', '%e %b %Y %T'),
	(156, 'GT', 'America/Guatemala', '', '%b %e, %Y %r'),
	(157, 'GU', 'Pacific/Guam', '', '%e %b %Y %T'),
	(158, 'GW', 'Africa/Bissau', '', '%e %b %Y %T'),
	(159, 'GY', 'America/Guyana', '', '%b %e, %Y %r'),
	(160, 'HK', 'Asia/Hong_Kong', '', '%e %b %Y %T'),
	(161, 'HN', 'America/Tegucigalpa', '', '%b %e, %Y %r'),
	(162, 'HR', 'Europe/Zagreb', '', '%e %b %Y %T'),
	(163, 'HT', 'America/Port-au-Prince', '', '%b %e, %Y %r'),
	(164, 'HU', 'Europe/Budapest', '', '%e %b %Y %T'),
	(165, 'ID', 'Asia/Jakarta', 'Java & Sumatra', '%e %b %Y %T'),
	(166, 'ID', 'Asia/Pontianak', 'west & central Borneo', '%e %b %Y %T'),
	(167, 'ID', 'Asia/Ujung_Pandang', 'east & south Borneo, Celebes, Bali, Nusa Tengarra, west Timor', '%e %b %Y %T'),
	(168, 'ID', 'Asia/Jayapura', 'Irian Jaya & the Moluccas', '%e %b %Y %T'),
	(169, 'IE', 'Europe/Dublin', '', '%e %b %Y %T'),
	(170, 'IL', 'Asia/Jerusalem', '', '%e %b %Y %T'),
	(171, 'IN', 'Asia/Calcutta', '', '%e %b %Y %T'),
	(172, 'IO', 'Indian/Chagos', '', '%e %b %Y %T'),
	(173, 'IQ', 'Asia/Baghdad', '', '%e %b %Y %T'),
	(174, 'IR', 'Asia/Tehran', '', '%e %b %Y %T'),
	(175, 'IS', 'Atlantic/Reykjavik', '', '%e %b %Y %T'),
	(176, 'IT', 'Europe/Rome', '', '%e %b %Y %T'),
	(177, 'JM', 'America/Jamaica', '', '%b %e, %Y %r'),
	(178, 'JO', 'Asia/Amman', '', '%e %b %Y %T'),
	(179, 'JP', 'Asia/Tokyo', '', '%e %b %Y %T'),
	(180, 'KE', 'Africa/Nairobi', '', '%e %b %Y %T'),
	(181, 'KG', 'Asia/Bishkek', '', '%e %b %Y %T'),
	(182, 'KH', 'Asia/Phnom_Penh', '', '%e %b %Y %T'),
	(183, 'KI', 'Pacific/Tarawa', 'Gilbert Islands', '%e %b %Y %T'),
	(184, 'KI', 'Pacific/Enderbury', 'Phoenix Islands', '%e %b %Y %T'),
	(185, 'KI', 'Pacific/Kiritimati', 'Line Islands', '%e %b %Y %T'),
	(186, 'KM', 'Indian/Comoro', '', '%e %b %Y %T'),
	(187, 'KN', 'America/St_Kitts', '', '%b %e, %Y %r'),
	(188, 'KP', 'Asia/Pyongyang', '', '%e %b %Y %T'),
	(189, 'KR', 'Asia/Seoul', '', '%e %b %Y %T'),
	(190, 'KW', 'Asia/Kuwait', '', '%e %b %Y %T'),
	(191, 'KY', 'America/Cayman', '', '%b %e, %Y %r'),
	(192, 'KZ', 'Asia/Almaty', 'east Kazakhstan', '%e %b %Y %T'),
	(193, 'KZ', 'Asia/Aqtobe', 'central Kazakhstan', '%e %b %Y %T'),
	(194, 'KZ', 'Asia/Aqtau', 'west Kazakhstan', '%e %b %Y %T'),
	(195, 'LA', 'Asia/Vientiane', '', '%e %b %Y %T'),
	(196, 'LB', 'Asia/Beirut', '', '%e %b %Y %T'),
	(197, 'LC', 'America/St_Lucia', '', '%b %e, %Y %r'),
	(198, 'LI', 'Europe/Vaduz', '', '%e %b %Y %T'),
	(199, 'LK', 'Asia/Colombo', '', '%e %b %Y %T'),
	(200, 'LR', 'Africa/Monrovia', '', '%e %b %Y %T'),
	(201, 'LS', 'Africa/Maseru', '', '%e %b %Y %T'),
	(202, 'LT', 'Europe/Vilnius', '', '%e %b %Y %T'),
	(203, 'LU', 'Europe/Luxembourg', '', '%e %b %Y %T'),
	(204, 'LV', 'Europe/Riga', '', '%e %b %Y %T'),
	(205, 'LY', 'Africa/Tripoli', '', '%e %b %Y %T'),
	(206, 'MA', 'Africa/Casablanca', '', '%e %b %Y %T'),
	(207, 'MC', 'Europe/Monaco', '', '%e %b %Y %T'),
	(208, 'MD', 'Europe/Chisinau', '', '%e %b %Y %T'),
	(209, 'MG', 'Indian/Antananarivo', '', '%e %b %Y %T'),
	(210, 'MH', 'Pacific/Majuro', 'most locations', '%e %b %Y %T'),
	(211, 'MH', 'Pacific/Kwajalein', 'Kwajalein', '%e %b %Y %T'),
	(212, 'MK', 'Europe/Skopje', '', '%e %b %Y %T'),
	(213, 'ML', 'Africa/Bamako', 'southwest Mali', '%e %b %Y %T'),
	(214, 'ML', 'Africa/Timbuktu', 'northeast Mali', '%e %b %Y %T'),
	(215, 'MM', 'Asia/Rangoon', '', '%e %b %Y %T'),
	(216, 'MN', 'Asia/Ulaanbaatar', 'most locations', '%e %b %Y %T'),
	(217, 'MN', 'Asia/Hovd', 'Bayan-Olgiy, Govi-Altai, Hovd, Uvs, Zavkhan', '%e %b %Y %T'),
	(218, 'MO', 'Asia/Macao', '', '%e %b %Y %T'),
	(219, 'MP', 'Pacific/Saipan', '', '%e %b %Y %T'),
	(220, 'MQ', 'America/Martinique', '', '%b %e, %Y %r'),
	(221, 'MR', 'Africa/Nouakchott', '', '%e %b %Y %T'),
	(222, 'MS', 'America/Montserrat', '', '%b %e, %Y %r'),
	(223, 'MT', 'Europe/Malta', '', '%e %b %Y %T'),
	(224, 'MU', 'Indian/Mauritius', '', '%e %b %Y %T'),
	(225, 'MV', 'Indian/Maldives', '', '%e %b %Y %T'),
	(226, 'MW', 'Africa/Blantyre', '', '%e %b %Y %T'),
	(227, 'MX', 'America/Mexico_City', 'Central Time - most locations', '%b %e, %Y %r'),
	(228, 'MX', 'America/Cancun', 'Central Time - Quintana Roo', '%b %e, %Y %r'),
	(229, 'MX', 'America/Merida', 'Central Time - Campeche, Yucatan', '%b %e, %Y %r'),
	(230, 'MX', 'America/Monterrey', 'Central Time - Coahuila, Durango, Nuevo Leon, Tamaulipas', '%b %e, %Y %r'),
	(231, 'MX', 'America/Mazatlan', 'Mountain Time - S Baja, Nayarit, Sinaloa', '%b %e, %Y %r'),
	(232, 'MX', 'America/Chihuahua', 'Mountain Time - Chihuahua', '%b %e, %Y %r'),
	(233, 'MX', 'America/Hermosillo', 'Mountain Standard Time - Sonora', '%b %e, %Y %r'),
	(234, 'MX', 'America/Tijuana', 'Pacific Time', '%b %e, %Y %r'),
	(235, 'MY', 'Asia/Kuala_Lumpur', 'peninsular Malaysia', '%e %b %Y %T'),
	(236, 'MY', 'Asia/Kuching', 'Sabah & Sarawak', '%e %b %Y %T'),
	(237, 'MZ', 'Africa/Maputo', '', '%e %b %Y %T'),
	(238, 'NA', 'Africa/Windhoek', '', '%e %b %Y %T'),
	(239, 'NC', 'Pacific/Noumea', '', '%e %b %Y %T'),
	(240, 'NE', 'Africa/Niamey', '', '%e %b %Y %T'),
	(241, 'NF', 'Pacific/Norfolk', '', '%e %b %Y %T'),
	(242, 'NG', 'Africa/Lagos', '', '%e %b %Y %T'),
	(243, 'NI', 'America/Managua', '', '%b %e, %Y %r'),
	(244, 'NL', 'Europe/Amsterdam', '', '%e %b %Y %T'),
	(245, 'NO', 'Europe/Oslo', '', '%e %b %Y %T'),
	(246, 'NP', 'Asia/Katmandu', '', '%e %b %Y %T'),
	(247, 'NR', 'Pacific/Nauru', '', '%e %b %Y %T'),
	(248, 'NU', 'Pacific/Niue', '', '%e %b %Y %T'),
	(249, 'NZ', 'Pacific/Auckland', 'most locations', '%e %b %Y %T'),
	(250, 'NZ', 'Pacific/Chatham', 'Chatham Islands', '%e %b %Y %T'),
	(251, 'OM', 'Asia/Muscat', '', '%e %b %Y %T'),
	(252, 'PA', 'America/Panama', '', '%b %e, %Y %r'),
	(253, 'PE', 'America/Lima', '', '%b %e, %Y %r'),
	(254, 'PF', 'Pacific/Tahiti', 'Society Islands', '%e %b %Y %T'),
	(255, 'PF', 'Pacific/Marquesas', 'Marquesas Islands', '%e %b %Y %T'),
	(256, 'PF', 'Pacific/Gambier', 'Gambier Islands', '%e %b %Y %T'),
	(257, 'PG', 'Pacific/Port_Moresby', '', '%e %b %Y %T'),
	(258, 'PH', 'Asia/Manila', '', '%e %b %Y %T'),
	(259, 'PK', 'Asia/Karachi', '', '%e %b %Y %T'),
	(260, 'PL', 'Europe/Warsaw', '', '%e %b %Y %T'),
	(261, 'PM', 'America/Miquelon', '', '%b %e, %Y %r'),
	(262, 'PN', 'Pacific/Pitcairn', '', '%e %b %Y %T'),
	(263, 'PR', 'America/Puerto_Rico', '', '%b %e, %Y %r'),
	(264, 'PS', 'Asia/Gaza', '', '%e %b %Y %T'),
	(265, 'PT', 'Europe/Lisbon', 'mainland', '%e %b %Y %T'),
	(266, 'PT', 'Atlantic/Madeira', 'Madeira Islands', '%e %b %Y %T'),
	(267, 'PT', 'Atlantic/Azores', 'Azores', '%e %b %Y %T'),
	(268, 'PW', 'Pacific/Palau', '', '%e %b %Y %T'),
	(269, 'PY', 'America/Asuncion', '', '%b %e, %Y %r'),
	(270, 'QA', 'Asia/Qatar', '', '%e %b %Y %T'),
	(271, 'RE', 'Indian/Reunion', '', '%e %b %Y %T'),
	(272, 'RO', 'Europe/Bucharest', '', '%e %b %Y %T'),
	(273, 'RU', 'Europe/Kaliningrad', 'Moscow-01 - Kaliningrad', '%e %b %Y %T'),
	(274, 'RU', 'Europe/Moscow', 'Moscow+00 - west Russia', '%e %b %Y %T'),
	(275, 'RU', 'Europe/Samara', 'Moscow+01 - Caspian Sea', '%e %b %Y %T'),
	(276, 'RU', 'Asia/Yekaterinburg', 'Moscow+02 - Urals', '%e %b %Y %T'),
	(277, 'RU', 'Asia/Omsk', 'Moscow+03 - west Siberia', '%e %b %Y %T'),
	(278, 'RU', 'Asia/Novosibirsk', 'Moscow+03 - Novosibirsk', '%e %b %Y %T'),
	(279, 'RU', 'Asia/Krasnoyarsk', 'Moscow+04 - Yenisei River', '%e %b %Y %T'),
	(280, 'RU', 'Asia/Irkutsk', 'Moscow+05 - Lake Baikal', '%e %b %Y %T'),
	(281, 'RU', 'Asia/Yakutsk', 'Moscow+06 - Lena River', '%e %b %Y %T'),
	(282, 'RU', 'Asia/Vladivostok', 'Moscow+07 - Amur River', '%e %b %Y %T'),
	(283, 'RU', 'Asia/Magadan', 'Moscow+08 - Magadan & Sakhalin', '%e %b %Y %T'),
	(284, 'RU', 'Asia/Kamchatka', 'Moscow+09 - Kamchatka', '%e %b %Y %T'),
	(285, 'RU', 'Asia/Anadyr', 'Moscow+10 - Bering Sea', '%e %b %Y %T'),
	(286, 'RW', 'Africa/Kigali', '', '%e %b %Y %T'),
	(287, 'SA', 'Asia/Riyadh', '', '%e %b %Y %T'),
	(288, 'SB', 'Pacific/Guadalcanal', '', '%e %b %Y %T'),
	(289, 'SC', 'Indian/Mahe', '', '%e %b %Y %T'),
	(290, 'SD', 'Africa/Khartoum', '', '%e %b %Y %T'),
	(291, 'SE', 'Europe/Stockholm', '', '%e %b %Y %T'),
	(292, 'SG', 'Asia/Singapore', '', '%e %b %Y %T'),
	(293, 'SH', 'Atlantic/St_Helena', '', '%e %b %Y %T'),
	(294, 'SI', 'Europe/Ljubljana', '', '%e %b %Y %T'),
	(295, 'SJ', 'Arctic/Longyearbyen', 'Svalbard', '%e %b %Y %T'),
	(296, 'SJ', 'Atlantic/Jan_Mayen', 'Jan Mayen', '%e %b %Y %T'),
	(297, 'SK', 'Europe/Bratislava', '', '%e %b %Y %T'),
	(298, 'SL', 'Africa/Freetown', '', '%e %b %Y %T'),
	(299, 'SM', 'Europe/San_Marino', '', '%e %b %Y %T'),
	(300, 'SN', 'Africa/Dakar', '', '%e %b %Y %T'),
	(301, 'SO', 'Africa/Mogadishu', '', '%e %b %Y %T'),
	(302, 'SR', 'America/Paramaribo', '', '%b %e, %Y %r'),
	(303, 'ST', 'Africa/Sao_Tome', '', '%e %b %Y %T'),
	(304, 'SV', 'America/El_Salvador', '', '%b %e, %Y %r'),
	(305, 'SY', 'Asia/Damascus', '', '%e %b %Y %T'),
	(306, 'SZ', 'Africa/Mbabane', '', '%e %b %Y %T'),
	(307, 'TC', 'America/Grand_Turk', '', '%b %e, %Y %r'),
	(308, 'TD', 'Africa/Ndjamena', '', '%e %b %Y %T'),
	(309, 'TF', 'Indian/Kerguelen', '', '%e %b %Y %T'),
	(310, 'TG', 'Africa/Lome', '', '%e %b %Y %T'),
	(311, 'TH', 'Asia/Bangkok', '', '%e %b %Y %T'),
	(312, 'TJ', 'Asia/Dushanbe', '', '%e %b %Y %T'),
	(313, 'TK', 'Pacific/Fakaofo', '', '%e %b %Y %T'),
	(314, 'TM', 'Asia/Ashgabat', '', '%e %b %Y %T'),
	(315, 'TN', 'Africa/Tunis', '', '%e %b %Y %T'),
	(316, 'TO', 'Pacific/Tongatapu', '', '%e %b %Y %T'),
	(317, 'TP', 'Asia/Dili', '', '%e %b %Y %T'),
	(318, 'TR', 'Europe/Istanbul', '', '%e %b %Y %T'),
	(319, 'TT', 'America/Port_of_Spain', '', '%b %e, %Y %r'),
	(320, 'TV', 'Pacific/Funafuti', '', '%e %b %Y %T'),
	(321, 'TW', 'Asia/Taipei', '', '%e %b %Y %T'),
	(322, 'TZ', 'Africa/Dar_es_Salaam', '', '%e %b %Y %T'),
	(323, 'UA', 'Europe/Kiev', 'most locations', '%e %b %Y %T'),
	(324, 'UA', 'Europe/Uzhgorod', 'Ruthenia', '%e %b %Y %T'),
	(325, 'UA', 'Europe/Zaporozhye', 'Zaporozh\'ye, E Lugansk', '%e %b %Y %T'),
	(326, 'UA', 'Europe/Simferopol', 'central Crimea', '%e %b %Y %T'),
	(327, 'UG', 'Africa/Kampala', '', '%e %b %Y %T'),
	(328, 'UM', 'Pacific/Johnston', 'Johnston Atoll', '%e %b %Y %T'),
	(329, 'UM', 'Pacific/Midway', 'Midway Islands', '%e %b %Y %T'),
	(330, 'UM', 'Pacific/Wake', 'Wake Island', '%e %b %Y %T'),
	(331, 'US', 'America/New_York', 'Eastern Time', '%b %e, %Y %r'),
	(332, 'US', 'America/Detroit', 'Eastern Time - Michigan - most locations', '%b %e, %Y %r'),
	(333, 'US', 'America/Louisville', 'Eastern Time - Kentucky - Louisville area', '%b %e, %Y %r'),
	(334, 'US', 'America/Kentucky/Monticello', 'Eastern Time - Kentucky - Wayne County', '%b %e, %Y %r'),
	(335, 'US', 'America/Indianapolis', 'Eastern Standard Time - Indiana - most locations', '%b %e, %Y %r'),
	(336, 'US', 'America/Indiana/Marengo', 'Eastern Standard Time - Indiana - Crawford County', '%b %e, %Y %r'),
	(337, 'US', 'America/Indiana/Knox', 'Eastern Standard Time - Indiana - Starke County', '%b %e, %Y %r'),
	(338, 'US', 'America/Indiana/Vevay', 'Eastern Standard Time - Indiana - Switzerland County', '%b %e, %Y %r'),
	(339, 'US', 'America/Chicago', 'Central Time', '%b %e, %Y %r'),
	(340, 'US', 'America/Menominee', 'Central Time - Michigan - Wisconsin border', '%b %e, %Y %r'),
	(341, 'US', 'America/Denver', 'Mountain Time', '%b %e, %Y %r'),
	(342, 'US', 'America/Boise', 'Mountain Time - south Idaho & east Oregon', '%b %e, %Y %r'),
	(343, 'US', 'America/Shiprock', 'Mountain Time - Navajo', '%b %e, %Y %r'),
	(344, 'US', 'America/Phoenix', 'Mountain Standard Time - Arizona', '%b %e, %Y %r'),
	(345, 'US', 'America/Los_Angeles', 'Pacific Time', '%b %e, %Y %r'),
	(346, 'US', 'America/Anchorage', 'Alaska Time', '%b %e, %Y %r'),
	(347, 'US', 'America/Juneau', 'Alaska Time - Alaska panhandle', '%b %e, %Y %r'),
	(348, 'US', 'America/Yakutat', 'Alaska Time - Alaska panhandle neck', '%b %e, %Y %r'),
	(349, 'US', 'America/Nome', 'Alaska Time - west Alaska', '%b %e, %Y %r'),
	(350, 'US', 'America/Adak', 'Aleutian Islands', '%b %e, %Y %r'),
	(351, 'US', 'Pacific/Honolulu', 'Hawaii', '%e %b %Y %T'),
	(352, 'UY', 'America/Montevideo', '', '%b %e, %Y %r'),
	(353, 'UZ', 'Asia/Samarkand', 'west Uzbekistan', '%e %b %Y %T'),
	(354, 'UZ', 'Asia/Tashkent', 'east Uzbekistan', '%e %b %Y %T'),
	(355, 'VA', 'Europe/Vatican', '', '%e %b %Y %T'),
	(356, 'VC', 'America/St_Vincent', '', '%b %e, %Y %r'),
	(357, 'VE', 'America/Caracas', '', '%b %e, %Y %r'),
	(358, 'VG', 'America/Tortola', '', '%b %e, %Y %r'),
	(359, 'VI', 'America/St_Thomas', '', '%b %e, %Y %r'),
	(360, 'VN', 'Asia/Saigon', '', '%e %b %Y %T'),
	(361, 'VU', 'Pacific/Efate', '', '%e %b %Y %T'),
	(362, 'WF', 'Pacific/Wallis', '', '%e %b %Y %T'),
	(363, 'WS', 'Pacific/Apia', '', '%e %b %Y %T'),
	(364, 'YE', 'Asia/Aden', '', '%e %b %Y %T'),
	(365, 'YT', 'Indian/Mayotte', '', '%e %b %Y %T'),
	(366, 'YU', 'Europe/Belgrade', '', '%e %b %Y %T'),
	(367, 'ZA', 'Africa/Johannesburg', '', '%e %b %Y %T'),
	(368, 'ZM', 'Africa/Lusaka', '', '%e %b %Y %T'),
	(369, 'ZW', 'Africa/Harare', '', '%e %b %Y %T');
